### ISSUE TITLE
doesnt run properly

### ISSUE THREAD

**Issue by zzzzz0001** [pgadmin-org/pgagent#24]
i installed pgagent from stack builder and from pgadmin and also directly from the postgres shell and all 3 times, the pgagent would only work on the deafult database "postgres" created by the postgres. i did try changing stuff in pgpass so that pgagent can access other databases too but it never worked. I cant see any problem as nothing is being logged about this in the log files.

**Comment by akshay-joshi** [comment]
@zzzzz0001 

Can you please provide some screenshots or exact reproduction steps?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
