### ISSUE TITLE
pgagent log rotation changes owner of logfile to default

### ISSUE THREAD

**Issue by Pyr0Texn1c** [pgadmin-org/pgagent#35]
pgagent service is running under postgres user account, but logfile (/var/log/pgagent_16.log) is created with ownership of pgagent:pgagent after rotation.
[pgagent.txt](https://github.com/pgadmin-org/pgagent/files/14279431/pgagent.txt)

**Comment by dpage** [comment]
pgAgent can only create log files owned by the user it runs as - it doesn't have any code to try to write logs as a different user. You should check the systemd unit file and logrotate (or whatever you are using) are configured appropriately.
