### ISSUE TITLE
Job finishes successfully but reruns unwanted!!!

### ISSUE THREAD

**Issue by ArashMasroor** [pgadmin-org/pgagent#37]
Hi,
I have a pgagent instance installed on Windows and Linux.
In both platforms I created one Job and multiple Job steps. It starts at the time scheduled and finishes successfully.
But reruns again and again.
I do upload some pics.

My schedule:
![1](https://github.com/user-attachments/assets/d51a84ee-556f-4f11-a7ba-4729b21cef5a)
The History
![2](https://github.com/user-attachments/assets/0d1fcb1a-85ab-414c-804a-5d22c1999d2c)

**Comment by dpage** [comment]
What do you have defined on the Repeat tab?

**Comment by ArashMasroor** [comment]
Nothing at all.
![2-RepeatTab](https://github.com/user-attachments/assets/b93bb017-fb6e-4ad4-b223-e52970262229)

**Comment by dpage** [comment]
Hmm, yeah, I suspect that's why. I don't remember us ever testing for "one shot" jobs. We'll have to dig into that.

**Comment by ArashMasroor** [comment]
Can I count on any result soon? If not what other solutions do you suggest?
I just need to run a command,Only once a week at a certain time.

**Comment by akshay-joshi** [comment]
@ArashMasroor 

Let us debug and check the actual cause. Give us some time.

**Comment by dpage** [comment]
Oh, well if you're running the job weekly, then just setup the schedule on the "Repeat" tab as normal - I'd suggest you select the weekday and the hour and minute to run at.

I believe the issue you've hit is only occurring because you haven't specified any repeat options, which is unusual.

**Comment by ArashMasroor** [comment]
This is the change I just made. Let's see what happens.

![2-RepeatTab2](https://github.com/user-attachments/assets/73b7513f-f77f-46d4-8fcf-3e2f6a7c0e94)

**Comment by dpage** [comment]
That should work. You don't actually need to specify the month though - the fields all default to "*", following the way cron works.

That is in fact, where I suspect the issue comes from with your original config. Because you didn't specify anything at all, it results in a "run every minute" schedule, starting from the start date/time.

**Comment by akshay-joshi** [comment]
Which version of pgAdmin 4 are you using?

**Comment by ArashMasroor** [comment]
Works fine in Windows. 

![2-RepeatTab2-Result](https://github.com/user-attachments/assets/cc058c8d-4c12-490e-83cc-5ca810758277)

I changed my schedule in Linux.

![1-Linux-GeneralTab](https://github.com/user-attachments/assets/0ca6a0fa-48b5-4a42-9c14-7f8be3489db3)

**Comment by ArashMasroor** [comment]
Linux;

![pgadminLinuxVer](https://github.com/user-attachments/assets/b1c01ce6-e8a8-4bf7-95fc-604fd7e8ac23)

Windows;
![pgadminWinVer](https://github.com/user-attachments/assets/13b27b9d-c9f0-4e91-8c85-368c3429829e)

**Comment by ArashMasroor** [comment]
Nothing happens,I think the Linux version has crashed but the process is running!!!

`amuser@test-pg-scheduler:~$ ps aux | grep pgagent
amuser      1352  0.0  0.5  98328 10640 ?        S    Jul29   1:15 /usr/bin/pgagent -l 1 -s /var/log/pgagent/pgagent.log hostaddr=127.0.0.1 dbname=postgres user=postgres
`

**Comment by ArashMasroor** [comment]
It worked in Linux too.

dpage  I am really grateful.
